horarioFontanProyecto/horarioFontanProyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views
urlpatterns = [
    path('estudiantes/', include('estudiantes.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('admin/', admin.site.urls),
    path('', views.vista_principal )
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:  # Asegúrate de que esto solo esté en modo desarrollo
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

horarioFontanProyecto/usuarios/urls.py
from django.urls import path
from . import views


# usuarios/..
app_name= 'usuarios'

urlpatterns = [
    path('', views.inicio, name='vista_inicio'),
    path('registro/', views.registro_usuario, name='vista_registro_usuario'),
    path('logout/', views.logout_user, name='logout'),
    path('perfil_personal/', views.perfil_usuario, name='perfil_usuario'),
    path('perfil_modificar/', views.perfil_modificar, name='perfil_modificar'),
]

horarioFontanProyecto/estudiantes/models.py
# estudiantes/models.py
from django.db import models
from django.contrib.auth.models import User

class Estudiante(models.Model):
    nombre = models.CharField(max_length=255)
    apellido = models.CharField(max_length=255)
    cedula = models.BigIntegerField(unique=True)
    email = models.EmailField(unique=True)
    nivel_autonomia = models.CharField(max_length=50)
    vacaciones_prolongadas = models.BooleanField(default=False)
    grado = models.CharField(max_length=50)
    taller = models.ForeignKey('horarios.Taller', on_delete=models.SET_NULL, null=True, blank=True)
    #usuario = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    tutor = models.ForeignKey('usuarios.Tutor', on_delete=models.SET_NULL, null=True, blank=True)
    tutor = models.ForeignKey('usuarios.Tutor', on_delete=models.SET_NULL, null=True, blank=True)
    foto = models.ImageField(upload_to='estudiantes/images', default='estudiantes/images/DSC_137999.jpg', blank=True, null=True)
    foto2 = models.ImageField(upload_to='estudiantes/images', default='estudiantes/images/DSC_137999.jpg', blank=True, null=True)


class EstudianteTaller(models.Model):
    estudiante = models.ForeignKey(Estudiante, on_delete=models.CASCADE, null=True)
    taller = models.ForeignKey('horarios.Taller', on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        unique_together = ('estudiante', 'taller')

horarioFontanProyecto/horarios/models.py
# horarios/models.py
from django.db import models
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

class Taller(models.Model):
    nombre = models.CharField(max_length=255)
    descripcion = models.TextField(blank=True, null=True)
    cupo_maximo = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(100)]
    )
    cupo_actual = models.IntegerField(default=0)
    tutor = models.ForeignKey('usuarios.Tutor', on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"{self.nombre} (Cupo: {self.cupo_actual}/{self.cupo_maximo})"



class Bloque(models.Model):
    nombre = models.CharField(max_length=50)
    hora_inicio = models.TimeField()
    hora_fin = models.TimeField()
    tipo = models.CharField(max_length=50)  # Ejemplo: 'clase', 'descanso', etc.

class Horario(models.Model):
    estudiante = models.ForeignKey('estudiantes.Estudiante', on_delete=models.CASCADE, null=True, blank=True)
    taller = models.ForeignKey(Taller, on_delete=models.CASCADE, null=True, blank=True)
    tutor = models.ForeignKey('usuarios.Tutor', on_delete=models.CASCADE, null=True)
    bloque = models.ForeignKey(Bloque, on_delete=models.CASCADE, null=True, blank=True)

horarioFontanProyecto/usuarios/models.py
# usuarios/models.py
from django.contrib.auth.models import User
from django.db import models
import os

# Cambiar el path para usar 'media/images'
def user_directory_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = f"{instance.usuario.username}.{ext}"
    return os.path.join('images', filename)  # Archivos serán guardados en 'media/images'

class Tutor(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    foto = models.ImageField(upload_to=user_directory_path, blank=True, null=True)

    def __str__(self):
        return f"Tutor: {self.usuario.username if self.usuario else 'Sin usuario asignado'}"



# usuarios/models.py

# class Usuario(models.Model):
#     user = models.OneToOneField(User, on_delete=models.CASCADE)
#     rol = models.CharField(max_length=50)
#     fecha_creacion = models.DateField(auto_now_add=True)
#     ultimo_login = models.DateTimeField(null=True, blank=True)

#     def __str__(self):
#         return f"Perfil de {self.user.username}"

horarioFontanProyecto/usuarios/forms.py
# forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.utils.safestring import mark_safe

class SignUpForm(UserCreationForm):
    USER_TYPE_CHOICES = [
        ('tutor', 'Tutor'),
        ('admin', 'Admin'),
    ]
    
    user_type = forms.ChoiceField(
        choices=USER_TYPE_CHOICES,
        required=True,
        widget=forms.Select(attrs={
            'class': 'form-control',
            'placeholder': 'Tipo de usuario',
        }),
        label=''
    )

    foto = forms.ImageField(
        required=False,
        widget=forms.ClearableFileInput(attrs={
            'class': 'form-control',
            'placeholder': 'Foto del Tutor',
        }),
        label='Foto del Tutor'
    )

    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(attrs={
            'class': 'form-control',
            'placeholder': 'Correo electrónico',
        }),
        label='',
        help_text=mark_safe('<span class="form-text text-muted"><small>Debe ser un correo que termine en @colegiofontan.edu.co.</small></span>')
    )

    invitation_code = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': 'Código de invitación',
        }),
        label='',
    )

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2', 'invitation_code', 'user_type', 'foto')

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'Nombre de usuario'
        self.fields['username'].label = ''
        self.fields['username'].help_text = mark_safe(
            '<span style="color:blue;" class="form-text text-muted"><small>Debe ser 20 caracteres o menos. Solo letras, números y @/./+/-/_</small></span>'
        )

        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['placeholder'] = 'Correo electrónico'
        self.fields['email'].label = ''
        self.fields['email'].help_text = mark_safe('<span class="form-text text-muted"><small>Debe ser un correo que termine en @colegiofontan.edu.co.</small></span>')

        self.fields['first_name'].widget.attrs['class'] = 'form-control'
        self.fields['first_name'].widget.attrs['placeholder'] = 'Nombre'
        self.fields['first_name'].label = ''

        self.fields['last_name'].widget.attrs['class'] = 'form-control'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Apellido'
        self.fields['last_name'].label = ''

        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['placeholder'] = 'Contraseña'
        self.fields['password1'].label = ''
        self.fields['password1'].help_text = mark_safe(
            '<ul class="form-text text-muted small">'
            '<li>Tu contraseña no puede ser muy parecida a tu nombre de usuario.</li>'
            '<li>Tu contraseña debe tener al menos 8 caracteres.</li>'
            '<li>Tu contraseña no puede ser una contraseña comúnmente usada.</li>'
            '<li>Tu contraseña no puede consistir únicamente en números.</li>'
            '</ul>'
        )

        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['placeholder'] = 'Confirma contraseña'
        self.fields['password2'].label = ''
        self.fields['password2'].help_text = mark_safe('<span class="form-text text-muted"><small>Ingresa la misma contraseña de antes, para confirmar.</small></span>')

        self.fields['invitation_code'].widget.attrs['class'] = 'form-control'
        self.fields['invitation_code'].widget.attrs['placeholder'] = 'Ingrese código de verificación'
        self.fields['invitation_code'].label = ''

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not email.endswith('@colegiofontan.edu.co'):
            raise ValidationError('El correo electrónico debe terminar en @colegiofontan.edu.co')
        return email

    def clean_invitation_code(self):
        code = self.cleaned_data.get('invitation_code')
        valid_codes = ['J3n@9Fq$LbZ2']  # Ejemplo de códigos válidos
        if code not in valid_codes:
            raise ValidationError('El código de invitación no es válido.')
        return code

horarioFontanProyecto/usuarios/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import SignUpForm
from .models import Tutor


def inicio(request):
    logout(request)
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return render(request, 'estudiantes/home.html')
        else:
            messages.error(request, "Error al iniciar sesión. Por favor, inténtalo de nuevo.")
            return render(request, 'usuarios/inicio.html')
    else:
        return render(request, 'usuarios/inicio.html')

def registro_usuario(request):
    logout(request)
    if request.method == 'POST':
        form = SignUpForm(request.POST, request.FILES)  
        if form.is_valid():
            user = form.save(commit=False)  # No guardar aún
            user.set_password(form.cleaned_data['password1'])
            user.save()  # Ahora guardar el usuario
            user_type = form.cleaned_data['user_type']
            
            if user_type == 'tutor':
                Tutor.objects.create(
                    usuario=user,
                    foto=form.cleaned_data.get('foto')
                )
            user = authenticate(username=form.cleaned_data['username'], password=form.cleaned_data['password1'])
            if user is not None:
                login(request, user)
                return render(request, 'estudiantes/home.html')
    else:
        form = SignUpForm()

    return render(request, 'usuarios/registro.html', {'form': form})




def logout_user(request):
	logout(request)
	messages.success(request, "Cerraste sesion correctamente...")
	return render(request, 'usuarios/inicio.html')


def perfil_usuario(request):
    tutor = Tutor.objects.get(usuario=request.user)
    return render(request, 'usuarios/perfil_usuario.html/', {'tutor': tutor})

def perfil_modificar(request):
    if request.method == 'POST':
        user = request.user
        user.first_name = request.POST.get('nombre')
        user.last_name = request.POST.get('apellido')
        user.email = request.POST.get('email')
        user.username = request.POST.get('username')

        password = request.POST.get('password')
        password2 = request.POST.get('password2')

        if password and password == password2:
            user.set_password(password)
        
        user.save()
        messages.success(request, '¡Perfil actualizado exitosamente!')
        return render(request, 'usuarios/perfil_usuario.html')

    return render(request, 'usuarios/perfil_modificar.html')

horarioFontanProyecto/usuarios/templates/usuarios/inicio.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="col-md-6 offset-md-3 space">
  <h1>Iniciar Sesión</h1>
  <br/>
  
  <form method="POST" action="/usuarios/">
    {% csrf_token %}
    <div class="mb-3">
        <input type="text" class="form-control" name="username" placeholder="Nombre de usuario" required>
    </div>
    <div class="mb-3">
        <input type="password" class="form-control" name="password" placeholder="Contraseña" required>
    </div>
    <button type="submit" class="btn btn-secondary">Iniciar sesión</button>
  </form>
</div>

{% endblock %}

horarioFontanProyecto/usuarios/templates/usuarios/perfil_modificar.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Modificar Perfil</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style_perfil_personal.css' %}">
</head>
<body>
    <div class="container">
        <h1>Modificar Datos del Perfil</h1>
        <form method="post" action="{% url 'usuarios:perfil_modificar' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_nombre">Nombre:</label>
                <input type="text" id="id_nombre" name="nombre" value="{{ user.first_name }}" required>
            </div>

            <div class="form-group">
                <label for="id_apellido">Apellido:</label>
                <input type="text" id="id_apellido" name="apellido" value="{{ user.last_name }}" required>
            </div>

            <div class="form-group">
                <label for="id_email">Correo Electrónico:</label>
                <input type="email" id="id_email" name="email" value="{{ user.email }}" required>
            </div>

            <div class="form-group">
                <label for="id_username">Nombre de Usuario:</label>
                <input type="text" id="id_username" name="username" value="{{ user.username }}" required>
            </div>

            <div class="form-group">
                <label for="id_password">Contraseña:</label>
                <input type="password" id="id_password" name="password">
            </div>

            <div class="form-group">
                <label for="id_password2">Confirmar Contraseña:</label>
                <input type="password" id="id_password2" name="password2">
            </div>

            <button type="submit" class="btn btn-primary">Guardar Cambios</button>
        </form>
    </div>
</body>
</html>

horarioFontanProyecto/usuarios/templates/usuarios/perfil_personal.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Modificar Perfil</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style_perfil_personal.css' %}">
</head>
<body>
    <div class="container">
        <h1>Modificar Datos del Perfil</h1>
        <form method="post" action="{% url 'usuarios:perfil_modificar' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_nombre">Nombre:</label>
                <input type="text" id="id_nombre" name="nombre" value="{{ user.first_name }}" required>
            </div>

            <div class="form-group">
                <label for="id_apellido">Apellido:</label>
                <input type="text" id="id_apellido" name="apellido" value="{{ user.last_name }}" required>
            </div>

            <div class="form-group">
                <label for="id_email">Correo Electrónico:</label>
                <input type="email" id="id_email" name="email" value="{{ user.email }}" required>
            </div>

            <div class="form-group">
                <label for="id_username">Nombre de Usuario:</label>
                <input type="text" id="id_username" name="username" value="{{ user.username }}" required>
            </div>

            <div class="form-group">
                <label for="id_password">Contraseña:</label>
                <input type="password" id="id_password" name="password">
            </div>

            <div class="form-group">
                <label for="id_password2">Confirmar Contraseña:</label>
                <input type="password" id="id_password2" name="password2">
            </div>

            <button type="submit" class="btn btn-primary">Guardar Cambios</button>
        </form>
    </div>
</body>
</html>

horarioFontanProyecto/usuarios/templates/usuarios/perfil_usuario.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="space2x">
    <div class="row mb-4">
      <div class="col-md-3">
        <div class="profile-image-container space-left2x">
            {% if tutor.foto %}
                <img src="{{ tutor.foto.url }}" alt="Foto de {{ tutor.usuario.username }}" class="profile-image">
            {% else %}
                <img src="{% static 'images/DSC_1379.jpg' %}" class="card-img-top" alt="Estudiante Image">
            {% endif %}
        </div>
      </div>
        <div class="col-md-6 d-flex flex-column justify-content-center">
            <h1 class="display-4">{{ user.first_name }} {{ user.last_name }}</h1>
            <h2 class="text-muted">Taller A</h2>
        </div>
    </div>

    <div class="row mb-4">
        <div class="col-md-12">
            <div class="d-flex justify-content-between align-items-center mb-3">
              <h4>.</h4>
                <div class="btn-group" role="group" aria-label="Toggle Schedule">
                    <button type="button" class="btn custom-toggle-btn" id="main-schedule-btn">Horario Principal</button>
                    <button type="button" class="btn custom-toggle-btn" id="recess-schedule-btn">Horario de descanso</button>
                </div>
            </div>
            <div class="card" style="height: 600px;" id="schedule-container">
                <div class="card-body">
                    <p id="main-schedule-content">Aquí va el contenido del horario principal.</p>
                    <p id="recess-schedule-content" style="display: none;">Aquí va el contenido del horario de recreos.</p>
                </div>
            </div>
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-md-7"></div>
        <div class="col-md-5 d-flex align-items-center justify-content-center">
            <a class="btn btn-lg btn-custom-modify" href="{% url 'usuarios:perfil_modificar' %}">Modificar perfil</a>
        </div>
    </div>
    <br><br><br>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script>
    $(document).ready(function() {
        $('#main-schedule-btn').click(function() {
            $('#main-schedule-content').show();
            $('#recess-schedule-content').hide();
            $('#main-schedule-btn').addClass('active').removeClass('inactive');
            $('#recess-schedule-btn').addClass('inactive').removeClass('active');
        });

        $('#recess-schedule-btn').click(function() {
            $('#main-schedule-content').hide();
            $('#recess-schedule-content').show();
            $('#main-schedule-btn').addClass('inactive').removeClass('active');
            $('#recess-schedule-btn').addClass('active').removeClass('inactive');
        });
    });
</script>
{% endblock %}

horarioFontanProyecto/usuarios/templates/usuarios/registro.html
{% extends 'base.html' %}
{% block content %}



<div class="col-md-6 offset-md-3 space">
<h1>Registro</h1>
<br/>

<form method="POST" action="" enctype="multipart/form-data">
	{% csrf_token %}
	{% if form.errors %}
			<div class="alert alert-warning alert-dismissible fade show" role="alert">
			  Tuviste un error al completar los datos
			  {% for field in form %}
			  	{% if field.errors %}
			  		{{ field.errors }}
			  	{% endif %}
			  {% endfor %}
			  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
			</div>
		{% endif %}

	{{ form.as_p }}

	<br/>
	  <button type="submit" class="btn btn-custom">Registrar</button>
	</form>



</div>




{% endblock %}