horarioFontanProyecto/estudiantes/urls.py
from django.urls import path
from . import views


app_name = 'estudiantes'
# estudiantes/..

urlpatterns = [
    path('perfil/<int:estudiante_id>/', views.detalle_perfil, name='detalle_perfil'),
    path('perfil/', views.vista_perfil, name='pagina-estudiantes'),
    path('', views.vista_home, name='vista_estudiantes'),
    path('registro_estudiante/', views.registro_estudiante, name='registro_estudiante'),
    path('search/', views.search, name='search'),
    #path('estudiantes_por_taller/<str:taller_id>/', views.estudiantes_por_taller, name='estudiantes_por_taller'),
]

horarioFontanProyecto/horarioFontanProyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views
urlpatterns = [
    path('estudiantes/', include('estudiantes.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('admin/', admin.site.urls),
    path('', views.vista_principal )
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:  # Asegúrate de que esto solo esté en modo desarrollo
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

horarioFontanProyecto/usuarios/urls.py
from django.urls import path
from . import views


# usuarios/..
app_name= 'usuarios'

urlpatterns = [
    path('', views.inicio, name='vista_inicio'),
    path('registro/', views.registro_usuario, name='vista_registro_usuario'),
    path('logout/', views.logout_user, name='logout'),
    path('perfil_personal/', views.perfil_usuario, name='perfil_usuario'),
    path('perfil_modificar/', views.perfil_modificar, name='perfil_modificar'),
]

horarioFontanProyecto/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Horarios Fontan</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <style>
        
.custom-navbar-bg {
  background-color: #064463 !important;
}

.vertical-navbar {
  position: fixed;
  top: 110px;
  left: 0;
  bottom: 0;
  width: 230px;
  background-color: #1C5471;
  overflow-y: hidden; /* Cambiado a hidden para evitar doble scroll */
  z-index: 1000;
}

.vertical-navbar .scroll-container {
  max-height: calc(100vh - 110px); /* Ajusta la altura para el scroll */
  overflow-y: auto;
}

.vertical-navbar ul {
  list-style-type: none;
  padding: 0;
  margin: 0;
  display: block;
}

.vertical-navbar ul li {
  padding-bottom: 25px;
}


.vertical-navbar ul li a {
  color: #fff;
  text-decoration: none;
  font-size: 20px;
  padding: 15px; /* Padding uniforme */
  display: block; /* Asegura que el enlace ocupe toda el área del elemento */
}

.vertical-navbar ul li a:hover {
  background-color: #064463;
  border-radius: 5px; /* Añade un borde redondeado al hover */
}

.container {
  padding-top: 60px; /* Ajusta según la altura de la barra de navegación */
}

.container-principal {
  max-width: 90%; 
  padding-left: 2rem;  
  padding-right: 2rem;
  margin-left: 250px; /* Añade margen para evitar superposición con la barra lateral */
}

.btn-custom {
  background-color: #064463;
  border-color: #064463;
  color: white;
  
}

.btn-custom:hover {
    background-color: #1C5471;
    border-color: #1C5471;
    color: white;
}

.btn-custom-modify {
  background-color: #1C5471;
  color: #ffffff;
  border: none;
  border-radius: 8px;
  padding: 12px 24px;
  font-size: 18px;
  font-weight: bold;
  text-transform: uppercase;
  transition: background-color 0.3s, transform 0.3s;
}

.btn-custom-modify:hover {
  background-color: #163E59;
  transform: scale(1.05);
  color: #f4f4f4;
}

.profile-image-container {
  width: 100%; 
  max-width: 230px; 
  height: 300px; 
  overflow: hidden; 
  display: flex;
  justify-content: center;
  align-items: center;
  border-radius: 8px; 
}

.profile-image-container img {
  width: auto; 
  height: 100%; 
  object-fit: cover; 
}


.custom-toggle-btn{
    background-color: #064463;
    border-color: #064463;
    color: white;
}
  
.custom-toggle-btn:hover {
    background-color: #1C5471;
    border-color: #1C5471;
    color: white;
}


</style>

  </head>
  <body>
    {% include 'navbar.html' %}

    <div class="container container-principal ">
      <br/>
      <div style="margin-top: 100px;">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-warning alert-dismissible fade show space" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
      {% endif %}
      {% block content %}
      {% endblock %}
      </div>
    </div> 
  </body>
</html>

horarioFontanProyecto/templates/index.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Horarios Fontan</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styling_index.css' %}">
    <title>Inicio Fontan</title>
</head>
<body>
    <main>
        <div class="welcome-message">
            <h1>¡Bienvenido a Horarios Fontan!</h1>
            <p>Tu lugar ideal para consultar los horarios de tus alumnos <br> de manera fácil y rápida.</p>
            <br><br><br><br><br>
            <a href="/usuarios/" class="btn-index">Iniciar Sesión</a>
            <a href="/usuarios/registro/" class="btn-index">Registrarse</a>
        </div>
    </main>
    <footer>
        <p>&copy; 2024 Horarios Fontan. Todos los derechos reservados.</p>
    </footer>
    
</body>
</html>

horarioFontanProyecto/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark custom-navbar-bg" style="height: 110px; position: fixed; width: 100%; z-index: 1000;">
  <div class="container-fluid">
    <a class="navbar-brand ms-5 me-auto" style="font-size: 25px;" href="/estudiantes/" >Colegio Fontan</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      {% if user.is_authenticated %}
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0 me-1">
        <li class="nav-item me-3">
          <a class="nav-link me-3">Tutores</a>
        </li>
        <li class="nav-item me-3">
          <a class="nav-link me-3" href="{% url 'usuarios:logout' %}">Cerrar Sesión</a>
        </li>
        <li class="nav-item me-3">
          <a class="nav-link me-3" href="{% url 'estudiantes:registro_estudiante' %}">Registrar Estudiantes</a>
        </li>  
        <li class="nav-item me-3">
          <form class="d-flex" action="{% url 'estudiantes:search' %}" method="GET">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="query">
            <button class="btn btn-outline-light" type="submit">Search</button>
          </form>
        </li>
        <li class="nav-item me-3">
          <a class="nav-link me-3 space-left" href="{% url 'usuarios:perfil_usuario' %}">
            <i class="fas fa-user fa-4x"></i>
          </a>
        </li>
      </ul>
      {% else %}
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0 me-1">
        <li class="nav-item me-3">
          <a class="nav-link me-3" href="{% url 'usuarios:vista_inicio' %}">Iniciar Sesión</a>
        </li>
        <li class="nav-item me-3">
          <a class="nav-link me-3" href="{% url 'usuarios:vista_registro_usuario' %}">Registrarse</a>
        </li>
      </ul>
      {% endif %}
    </div>
    
  </div>
</nav>