horarioFontanProyecto/estudiantes/urls.py
from django.urls import path
from . import views


app_name = 'estudiantes'
# estudiantes/..

urlpatterns = [
    path('perfil/<int:estudiante_id>/', views.detalle_perfil, name='detalle_perfil'),
    path('perfil/', views.vista_perfil, name='pagina-estudiantes'),
    path('', views.vista_home, name='vista_estudiantes'),
    path('registro_estudiante/', views.registro_estudiante, name='registro_estudiante'),
    path('search/', views.search, name='search'),
    #path('estudiantes_por_taller/<str:taller_id>/', views.estudiantes_por_taller, name='estudiantes_por_taller'),
]

horarioFontanProyecto/horarioFontanProyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views
urlpatterns = [
    path('estudiantes/', include('estudiantes.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('admin/', admin.site.urls),
    path('', views.vista_principal )
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:  # Asegúrate de que esto solo esté en modo desarrollo
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

horarioFontanProyecto/usuarios/urls.py
from django.urls import path
from . import views


# usuarios/..
app_name= 'usuarios'

urlpatterns = [
    path('', views.inicio, name='vista_inicio'),
    path('registro/', views.registro_usuario, name='vista_registro_usuario'),
    path('logout/', views.logout_user, name='logout'),
    path('perfil_personal/', views.perfil_usuario, name='perfil_usuario'),
    path('perfil_modificar/', views.perfil_modificar, name='perfil_modificar'),
]

horarioFontanProyecto/estudiantes/models.py
# estudiantes/models.py
from django.db import models
from django.contrib.auth.models import User

class Estudiante(models.Model):
    nombre = models.CharField(max_length=255)
    apellido = models.CharField(max_length=255)
    cedula = models.BigIntegerField(unique=True)
    email = models.EmailField(unique=True)
    nivel_autonomia = models.CharField(max_length=50)
    vacaciones_prolongadas = models.BooleanField(default=False)
    grado = models.CharField(max_length=50)
    taller = models.ForeignKey('horarios.Taller', on_delete=models.SET_NULL, null=True, blank=True)
    #usuario = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    tutor = models.ForeignKey('usuarios.Tutor', on_delete=models.SET_NULL, null=True, blank=True)
    tutor = models.ForeignKey('usuarios.Tutor', on_delete=models.SET_NULL, null=True, blank=True)
    foto = models.ImageField(upload_to='estudiantes/images', default='estudiantes/images/DSC_137999.jpg', blank=True, null=True)
    foto2 = models.ImageField(upload_to='estudiantes/images', default='estudiantes/images/DSC_137999.jpg', blank=True, null=True)


class EstudianteTaller(models.Model):
    estudiante = models.ForeignKey(Estudiante, on_delete=models.CASCADE, null=True)
    taller = models.ForeignKey('horarios.Taller', on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        unique_together = ('estudiante', 'taller')

horarioFontanProyecto/estudiantes/forms.py
# estudiantes/forms.py
from django import forms
from .models import Estudiante

class EstudianteForm(forms.ModelForm):
    class Meta:
        model = Estudiante
 
 
        fields = ['nombre', 'apellido', 'cedula',  'nivel_autonomia', 'vacaciones_prolongadas', 'grado', 'taller', 'foto', 'email']

def __init__(self, *args, **kwargs):
        super(EstudianteForm, self).__init__(*args, **kwargs)

        self.fields['nombre'].widget.attrs['class'] = 'form-control'
        self.fields['nombre'].widget.attrs['placeholder'] = 'Nombre estudiante'
        self.fields['nombre'].label = ''
        self.fields['nombre'].help_text = mark_safe('<span style="color:blue;" class="form-text text-muted"><small>Debe ser 20 caracteres o menos. Solo letras, números y @/./+/-/_</small></span>')

        self.fields['apellido'].widget.attrs['class'] = 'form-control'
        self.fields['apellido'].widget.attrs['placeholder'] = 'Apellido estudiante'
        self.fields['apellido'].label = ''
        self.fields['apellido'].help_text = mark_safe('')    

        self.fields['cedula'].widget.attrs['class'] = 'form-control'
        self.fields['cedula'].widget.attrs['placeholder'] = 'Cédula estudiante'
        self.fields['cedula'].label = ''
        self.fields['cedula'].help_text = mark_safe('')   

        self.fields['nivel_autonomia'].widget.attrs['class'] = 'form-control'
        self.fields['nivel_autonomia'].widget.attrs['placeholder'] = 'Nivel autonomia'
        self.fields['nivel_autonomia'].label = ''
        self.fields['nivel_autonomia'].help_text = mark_safe('')   

        self.fields['taller'].widget.attrs['class'] = 'form-control'
        self.fields['taller'].widget.attrs['placeholder'] = 'Taller Base'
        self.fields['taller'].label = ''
        self.fields['taller'].help_text = mark_safe('')   

        self.fields['grado'].widget.attrs['class'] = 'form-control'
        self.fields['grado'].widget.attrs['placeholder'] = 'Grado estudiante'
        self.fields['grado'].label = ''
        self.fields['grado'].help_text = mark_safe('')   

        self.fields['foto'].widget.attrs['class'] = 'form-control'
        self.fields['foto'].widget.attrs['placeholder'] = 'Grado estudiante'
        self.fields['foto'].label = ''
        self.fields['foto'].help_text = mark_safe('') 
        

horarioFontanProyecto/estudiantes/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound
from .models import Estudiante
from .forms import EstudianteForm
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView

# Create your views here.
def vista_perfil(request):
    # estudiantes/templates/estudiantes/perfil.html
    return render(request, 'estudiantes/perfil.html')


def vista_home(request):
    # estudiantes/templates/estudiantes/home.hmtl
    #query = not query
    estudiantes = Estudiante.objects.all()
    return render(request, 'estudiantes/home.html', {'estudiante':estudiantes})


def search(request):
    query = request.GET.get('query')
    estudiantes = Estudiante.objects.filter(nombre__icontains=query)
    return render(request, 'estudiantes/home.html', {'estudiantes': estudiantes, 'query': query})

# alumnos = {
#     "repre1": 'Nico',
#     "repre2": "Pedro",
#     "repre3": "Jose"
# }

def detalle_perfil(request, estudiante_id):
    try:
        estudiante = get_object_or_404(Estudiante, id=estudiante_id)
        return render(request, 'estudiantes/perfil.html', {'estudiante': estudiante})
    except:
        resultado = 'No se encuentra informacion de este estudiante'
        return HttpResponseNotFound(resultado)


def registro_estudiante(request):
    if request.method == 'POST':
        form = EstudianteForm(request.POST)
        if form.is_valid():
            Estudiante = form.save()
            Estudiante.nombre = form.cleaned_data['nombre']
            Estudiante.apellido = form.cleaned_data['apellido']
            Estudiante.cedula = form.cleaned_data['cedula']
            Estudiante.nivel_autonomia = form.cleaned_data['nivel_autonomia']
            Estudiante.taller = form.cleaned_data['taller']
            Estudiante.grado = form.cleaned_data['grado']
            Estudiante.foto= form.cleaned_data['foto']
            if Estudiante is not None:
                return render(request, 'estudiantes/home.html')
    else:
        form = EstudianteForm()

    return render(request, 'estudiantes/registro_estudiante.html', {'form': form})

#CUANDO YA ESTEN CREADO EL MODELO DE TALLER Y DE ESTUDIANTES, PARA QUE CADA TALLER REDIRIJA HACIA EL ADECUADO
#def estudiantes_por_taller(request, taller_id):
#    taller = Taller.objects.get(nombre=taller_id)
#   estudiantes = Estudiante.objects.filter(taller=taller)
#  return render(request, 'home.html', {'taller': taller, 'Estudiante': estudiantes})

horarioFontanProyecto/estudiantes/templates/estudiantes/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container-fluid">
  <nav class="vertical-navbar" style="height: 100vh; overflow-y: auto;">
    <div class="container">
      <ul>
        {% for letter in "ABCDEFGHIJKLMNOPQRSTUVWXYZ" %}
        <li class="nav-item">
          <a class="nav-link">Taller {{ letter }}</a>
        </li>
        {% endfor %}
      </ul>
    </div>
  </nav>
</div> 

<div class="container">
  <div class="row row-cols-1 row-cols-md-3 g-4">
      {% if query %}
          {% if estudiantes %}
              {% for estudiante in estudiantes %}
                  <div class="col">
                      <div class="card" style="width: 18rem;">
                          <img src="{% static 'images/DSC_1379.jpg' %}" class="card-img-top" alt="Imagen del estudiante">
                          <div class="card-body">
                              <h5 class="card-title">
                                  <a href="{% url 'estudiantes:detalle_perfil' estudiante.id %}">
                                      {{ estudiante.nombre }} {{ estudiante.apellido }}
                                  </a>
                              </h5>
                              <p class="card-text"><strong>Cedula:</strong> {{ estudiante.cedula }}</p>
                              <p class="card-text"><strong>Nivel:</strong> {{ estudiante.nivel_autonomia }}</p>
                          </div>
                      </div>
                  </div>
              {% endfor %}
          {% else %}
              <div class="col">
                  <h2>No se encontraron resultados para "{{ query }}"</h2>
              </div>
          {% endif %}
      {% else %}
          {% for estudiante in estudiantes %}
              <div class="col">
                  <div class="card" style="width: 18rem;">
                      <img src="{% static 'images/DSC_1379.jpg' %}" class="card-img-top" alt="Imagen del estudiante">
                      <div class="card-body">
                          <h5 class="card-title">
                            <a href="{% url 'estudiantes:detalle_estudiante' estudiante.id %}" target="_blank">
                                {{ estudiante.nombre }} {{ estudiante.apellido }}
                            </a>                            
                          </h5>
                          <p class="card-text"><strong>Cedula:</strong> {{ estudiante.cedula }}</p>
                          <p class="card-text"><strong>Nivel:</strong> {{ estudiante.nivel_autonomia }}</p>
                      </div>
                  </div>
              </div>
          {% endfor %}
      {% endif %}
  </div>
</div>

{% endblock %}

horarioFontanProyecto/estudiantes/templates/estudiantes/perfil.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="space2x">
    <div class="row mb-4">
        <div class="col-md-3">
            <div class="profile-image-container space-left2x">
                <img src="{{ estudiante.foto2.url }}" class="card-img-top" alt="Imagen del estudiante">
            </div>
        </div>

        <div class="container-fluid">
            <nav class="vertical-navbar" style="height: 100vh; overflow-y: auto;">
              <div class="container">
                <ul>
                  {% for letter in "ABCDEFGHIJKLMNOPQRSTUVWXYZ" %}
                  <li class="nav-item">
                    <a class="nav-link">Taller {{ letter }}</a>
                  </li>
                  {% endfor %}
                </ul>
              </div>
            </nav>
          </div> 

        <div class="container">
            <h1>Detalles del Estudiante</h1>
            <p><strong>Nombre:</strong> {{ estudiante.nombre }} {{ estudiante.apellido }}</p>
            <p><strong>Cédula:</strong> {{ estudiante.cedula }}</p>
            <p><strong>Nivel de autonomía:</strong> {{ estudiante.nivel_autonomia }}</p>
    </div>

    <div class="row mt-4" style="width: 100%;">
        <div class="col-md-12">
            <div class="card" style="height: 600px;">
                <div class="card-body">
                    <h4>Horario</h4>
                </div>
            </div>
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-md-7"></div>
        <div class="col-md-2 d-flex align-items-center justify-content-end">
            <button class="btn btn-custom">Añadir estudiante</button>
        </div>
        <div class="col-md-2 d-flex align-items-center justify-content-center">
            <button class="btn btn-danger">Eliminar estudiante</button>
        </div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
{% endblock %}

horarioFontanProyecto/estudiantes/templates/estudiantes/registro_estudiante.html
{% extends 'base.html' %}
{% block content %}



<div class="col-md-6 offset-md-3 space">
<h1>Registrar estudiantes</h1>
<br/>

<form method="POST" action="">
	{% csrf_token %}
	{% if form.errors %}
			<div class="alert alert-warning alert-dismissible fade show" role="alert">
			  Tuviste un error al completar los datos
			  {% for field in form %}
			  	{% if field.errors %}
			  		{{ field.errors }}
			  	{% endif %}
			  {% endfor %}
			  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
			</div>
		{% endif %}

	{{ form.as_p }}

	<br/>
	  <button type="submit" class="btn btn-custom">Registrar</button>
	</form>



</div>




{% endblock %}